### ISSUE TITLE
Error in Mikrotik Queue Sync Plugin

### ISSUE THREAD

**Issue by hansin1** [Ubiquiti-App/UCRM-plugins#195]
Notice: Undefined variable: ucrmFormatedList in /data/ucrm/data/plugins/mkt-queue-sync/classes/Synchronizer.php on line 220

Fatal error: Uncaught TypeError: Return value of MikrotikQueueSync\Synchronizer::formatUcrmListIpAddress() must be of the type array, null returned in /data/ucrm/data/plugins/mkt-queue-sync/classes/Synchronizer.php:220 Stack trace: #0 /data/ucrm/data/plugins/mkt-queue-sync/classes/Synchronizer.php(179): MikrotikQueueSync\Synchronizer->formatUcrmListIpAddress(Array) #1 /data/ucrm/data/plugins/mkt-queue-sync/classes/Synchronizer.php(130): MikrotikQueueSync\Synchronizer->getUcrmServiceList(Array) #2 /data/ucrm/data/plugins/mkt-queue-sync/public.php(49): MikrotikQueueSync\Synchronizer->sync() #3 /data/ucrm/data/plugins/mkt-queue-sync/public.php(51): {closure}() #4 /usr/src/ucrm/web/_plugins/mkt-queue-sync/public.php(3): require_once('/data/ucrm/data...') #5 {main} thrown in /data/ucrm/data/plugins/mkt-queue-sync/classes/Synchronizer.php on line 220

**Comment by j4ys0n** [comment]
I'm getting the same error.

I'm on RouterOS v6.46.7 (long-term)

**Comment by bergynator** [comment]
Anyone find a solution to this?

**Comment by bergynator** [comment]
I've finally found the solution. When I added customer to my UCRM, their services plan was set to "Quoted". When I set them to "Active" the error was gone and the queues was successfully added to my Mikrotik.

**Comment by solufi** [comment]
Where did you see the Quoted / Active function ? I have the same problem

**Comment by matei1337** [comment]
I still have this problem, can anyone help me?
